### ISSUE TITLE
Problem with Red Protect 7.3.0-b61 on API 7 Sponge Forge

### ISSUE THREAD

**Issue by Gunslito** [FabioZumbi12/RedProtect#235] opened 2018-01-09 04:32 UTC
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  spongeforge-1.12.2-2555-7.1.0-BETA-2825

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.3.0-b61-Universal

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Issue

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  If I put a region using /rp wand or /rp pos1 /rp pos2 and then when I walk into the region and use the command /rp flag it shows a blank page, on help there's a problem, quote:
"/rp flag:fl <flag> <value> - Change a flag value.
/rp Missing language string for cmdmanager.translation.flaggui:
Missing language string for cmdmanager.translation.flaggui.alias
- Open a visual gui to change flag values.
![image](https://user-images.githubusercontent.com/35160558/34705120-d2d1ed08-f4dc-11e7-8e7b-6a7998963a95.png)

**Comment by FabioZumbi12** [comment] 2018-01-10 22:32
This an issue caused by latest API7 updates. I need to fix.
For, dont use `/rp flag` (only on sponge).

(that missing language is fixed on latest)

**Comment by unstablecraft** [comment] 2018-01-17 16:38
translation issue is indeed fixed  only ./rp flag comes up empty in build 64 no errors where made by redprotect

**Comment by FabioZumbi12** [comment] 2018-01-18 00:06
Fixed on latest dev version http://areaz12server.net.br:8080/job/RedProtect
ref https://github.com/FabioZumbi12/RedProtect/commit/91e196bf966588e29c5168b94e05e12315426e16

**Closed by FabioZumbi12** 2018-01-18 00:06 UTC
Labels: Bug
