### ISSUE TITLE
When I promote people to high ranks in a region, it does not change their allow-place, allow-break  flags

### ISSUE THREAD

**Issue by coolcat93** [FabioZumbi12/RedProtect#26] opened 2016-02-28 17:37 UTC
On your wiki, it states: 

Member: Can build, break blocks, place blocks, open chests and other inventory blocks, interact with all redstones, doors, buttons and armor stands and interact with all animals.

It is a little buggy, I had some trouble trying to allow members to be able to break it. I think you should make naming the region unnecessary, and have it automatically do it for you, so you dont run into errors

**Comment by FabioZumbi12** [comment] 2016-02-28 23:22
Sorry but i dont mean what you say. The problem is the player cant build/break with flags allow-place, allow-break set or in general? Promoting player dont allow this players to build?

**Comment by FabioZumbi12** [comment] 2016-04-12 09:00
Have you tryed the latest versions? Still the problem?

**Comment by FabioZumbi12** [comment] 2016-05-04 21:13
Closing... if still, reopen the issue.

**Closed by FabioZumbi12** 2016-05-04 21:13 UTC
Labels: question
