### ISSUE TITLE
[BUG] Regular crash...

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#805] opened 2022-01-16 20:32 UTC
Hi,

With 1.18 there is a regular crash on my server when a new player does an claim, apparently a selection with their claim tool. Please fix this bug as soon as possible because it is really problematic...

Error : https://pastebin.com/1ATLDS17

I use the last dev version of this plugin and Paper 1.18.1.

**Comment by Komodroid** [comment] 2022-02-20 13:12
This plugin haven't been updated since 2020, sea yeah probably they won't fix anything. I will try to pull this source and understand the program and plugin structure and try to fix the various bugs by myself. If I succeed I will try to post a new gh repo

**Comment by aurel85** [comment] 2022-03-27 12:46
In the same with 1.18.2 : https://pastebin.com/bQvXWnfP

**Comment by comonier** [comment] 2022-03-29 03:56
From the log it doesn't seem to be an rp problem - your server crashed after a player took a boat ride as if it didn't have enough processing power and memory for the rendering of chunks that was happening at the speed it was happening.

**Comment by EpiCanard** [comment] 2022-04-03 09:29
@comonier the error come from method `RedProtect-7.7.3-b410-Universal.jar//br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RedProtectUtil.addBorder(RedProtectUtil.java:88` that consume way too much resources, it's why the server freeze and you see "move wrongly" errors.

**Comment by comonier** [comment] 2022-04-05 23:43
> @comonier the error come from method `RedProtect-7.7.3-b410-Universal.jar//br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RedProtectUtil.addBorder(RedProtectUtil.java:88` that consume way too much resources, it's why the server freeze and you see "move wrongly" errors.

ok i will check it

**Comment by aurel85** [comment] 2022-07-04 17:55
With 1.19 version a selection limit has been added so that solves the problem, in a way.

**Comment by aurel85** [comment] 2024-01-13 12:16
The problem was never really resolved in the end and it persists in 1.20.4 (and in previous versions)...
Please do something because it's really unstable for new players, the server crashes quickly...

https://pastebin.com/qECW9976

**Comment by FabioZumbi12** [comment] 2024-06-24 22:57
The problem stills? The method `addBorder` is called only by player! if you having issues with this in logs, prob someone is using a lot, os via command block/script.
Btw, any log appearing after this crash can be a false" positive, as redProtect try to listen player and mob actions all the time.

**Comment by FabioZumbi12** [comment] 2024-06-26 19:38
Looking into a detailed code, theres a setting `region-setting > border > intensity` to deny things like this. In bigger regions, render a border can cause server crash (but is rare, i cant reproduce in my server in any way with a lot bigger regions)

**Closed by FabioZumbi12** 2024-06-26 19:38 UTC
Labels: New Issue

**Comment by aurel85** [comment] 2024-06-26 21:38
The bug hasn't happened for a long time but I changed this setting anyway, thanks.
