### ISSUE TITLE
[BUG] Bug with selection calculation

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#614] opened 2020-04-08 14:10 UTC
Hi,

I use the last version of this plugin (310) and Paper 1.15.2.

My players have complained of problems with the size calculated when selecting the two claim points. So I decided to investigate and indeed there is a problem ... Here is the evidence on a straight line of 128 blocks :   

![Capture](https://user-images.githubusercontent.com/24486147/78794016-79ee7900-79b3-11ea-917a-1f268ffd69e4.PNG)
![Capture2](https://user-images.githubusercontent.com/24486147/78794026-7ce96980-79b3-11ea-8109-e082bf5e8457.PNG)

![capture3](https://user-images.githubusercontent.com/24486147/78794036-7fe45a00-79b3-11ea-8143-ed9d0c3d08c2.PNG)
![Capture4](https://user-images.githubusercontent.com/24486147/78794050-8246b400-79b3-11ea-95ce-886807d03401.PNG)

Compared to where I go to make my selection the result is not the same, how is it ? There must be a calculation problem with the blocks where we click.

Thank you in advance.

**Comment by Tiger780** [comment] 2020-04-09 17:48
Hi, i think i figured how it works. 
I will try to be clear.

If you claim an area from **x0/z0 to x9/z0**. It's a **10*1=10** block claim.
![image](https://user-images.githubusercontent.com/38769246/78922974-beebdb80-7a97-11ea-837e-96e0f55ba508.png)

But if you go **x0/z0 to x-9/z0**, it will be a **8*1=8** block claim, but we can count 10 blocks in the claim.
![image](https://user-images.githubusercontent.com/38769246/78923374-68cb6800-7a98-11ea-9863-a3263520d93d.png)
(Same problem when you go negative in X way or Z way)

So the problem come from area calculation with negatives coordinates.

My theory is that you calculate the X (and later Z) selection with coordinate then add 1 because from **x0 to x9** there is 10 blocks. 

In our example :
**x0/z0 to x9/z0** gives **(9-0)+1**. 
But when you're in negative coordinates, it goes **(-9-0)+1 = 8**. <- **wrong size**
You may use absolute value before add +1.

Here is how i think it works, hope i helped you!

**Comment by FabioZumbi12** [comment] 2020-04-10 02:27
Confirmed and fixed on latest dev build

**Closed by FabioZumbi12** 2020-04-10 02:27 UTC
Labels: New Issue
