### ISSUE TITLE
Protection bypass

### ISSUE THREAD

**Issue by linkjay** [FabioZumbi12/RedProtect#381] opened 2019-02-06 04:44 UTC
Platform: Sponge
Jar version:  RedProtect-7.5.5-b130-Universal.jar
Minecraft version:  1.12.2 with forge version 1.12.2-14.23.5.2768
What you want?:  Issue/bug with core addon.

There is an error for me hosting my 1.12.2 Sponge forge server where rails, boats, and end crystals all can bypass the build/minecart permissions. 

You can just place boats no matter what, but cannot break or interact with if the permissions say. You can also place and destroy end crystals no matter what. 

Here is what is spat out into logs when you use a rail without proper access in a build-protected zone:
I am having what I believe to be the same exact issue. For me, it doesn't matter what the flag is, non-admin users can place rails in a non-build-flagged zone. It does say this into console: 

`[23:37:11] [Server thread/ERROR] [Sponge]: /*                                                                      Maximum block processing 
depth exceeded!                                                                      */
[23:37:11] [Server thread/ERROR] [Sponge]: /**************************************************************************************************************************************************************************************/
[23:37:11] [Server thread/ERROR] [Sponge]: /* Sponge is still trying to process captured blocks after 100 iterations of depth-first processing. This is likely due to a mod doing something unusual. GeneralPhase{}{PostState}   */
[23:37:11] [Server thread/ERROR] [Sponge]: /* PhaseContext :                                                                                                                                                                     */
[23:37:11] [Server thread/ERROR] [Sponge]: /*     - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                                                                       */
[23:37:11] [Server thread/ERROR] [Sponge]: /*     - UnwindingState: PacketPhase{}{PlaceBlockPacketState}                                                                                                                         */
[23:37:11] [Server thread/ERROR] [Sponge]: /*     - UnwindingContext: BasicPacketContext{isCompleted=true}                                                                                                                       */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - Owner: EntityPlayerMP['Linkjayy'/10962, l='spawnland', x=4.68, y=149.00, z=2.64]                                                                                         */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - Source: EntityPlayerMP['Linkjayy'/10962, l='spawnland', x=4.68, y=149.00, z=2.64]                                                                                        */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                                                                   */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - PacketPlayer: EntityPlayerMP['Linkjayy'/10962, l='spawnland', x=4.68, y=149.00, z=2.64]                                                                                  */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - Packet: CPacketPlayerTryUseItemOnBlock{position=BlockPos{x=5, y=148, z=0}, placedBlockDirection=up, hand=MAIN_HAND, facingX=0.40330973, facingY=1.0, facingZ=0.89248914} */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - IgnoreCreative: false                                                                                                                                                    */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - ItemStackUsed: 64xtile.rail@0                                                                                                                                            */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - OpenContainer: null                                                                                                                                                      */
[23:37:11] [Server thread/ERROR] [Sponge]: /* Phases remaining :                                                                                                                                                                 */
[23:37:11] [Server thread/ERROR] [Sponge]: /*   - Phase: GeneralPhase{}{PostState}                                                                                                                                               */
[23:37:11] [Server thread/ERROR] [Sponge]: /*     Context:                                                                                                                                                                       */
[23:37:11] [Server thread/ERROR] [Sponge]: /*     - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                                                                       */
[23:37:11] [Server thread/ERROR] [Sponge]: /*     - UnwindingState: PacketPhase{}{PlaceBlockPacketState}                                                                                                                         */
[23:37:11] [Server thread/ERROR] [Sponge]: /*     - UnwindingContext: BasicPacketContext{isCompleted=true}                                                                                                                       */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - Owner: EntityPlayerMP['Linkjayy'/10962, l='spawnland', x=4.68, y=149.00, z=2.64]                                                                                         */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - Source: EntityPlayerMP['Linkjayy'/10962, l='spawnland', x=4.68, y=149.00, z=2.64]                                                                                        */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                                                                   */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - PacketPlayer: EntityPlayerMP['Linkjayy'/10962, l='spawnland', x=4.68, y=149.00, z=2.64]                                                                                  */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - Packet: CPacketPlayerTryUseItemOnBlock{position=BlockPos{x=5, y=148, z=0}, placedBlockDirection=up, hand=MAIN_HAND, facingX=0.40330973, facingY=1.0, facingZ=0.89248914} */
[23:37:11] [Server thread/ERROR] [Sponge]: /*         - IgnoreCreative: false                                                               `

**Comment by FabioZumbi12** [comment] 2019-03-18 01:52
The ender crystal, boat and minecart is fixed on latest dev build. That other console logs i cant reproduce!

**Closed by FabioZumbi12** 2019-03-18 01:52 UTC
Labels: Need Revision
