### ISSUE TITLE
[ERROR] [BUG] MySQL error?

### ISSUE THREAD

**Issue by 7h3ev1l** [FabioZumbi12/RedProtect#48] opened 2016-05-09 15:59 UTC
Config:

```
mysql:
  db-name: SurvivalServer1
  user-name: SurvivalServer1
  user-pass: g8gg2369gg2g9ggg
  host: '8.8.8.8.im.google'
  region-cache-minutes: 2
```

I tried with '' in host and without i get the same error ....????

Error:
```
[18:53:29] [Server thread/INFO]: [RedProtect] Enabling RedProtect v6.5.8
[18:53:29] [Server thread/INFO]: Redprotect: [Server version: 1.9.2-R0.1-SNAPSHOT][m
[18:53:29] [Server thread/INFO]: Redprotect: [All configurations loaded!][m
[18:53:29] [Server thread/INFO]: Redprotect: [Language file loaded - Using: EN-US][m
[18:53:29] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1
[18:53:29] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:53:29] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:53:29] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:53:29] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:53:29] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[18:53:29] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
[18:53:29] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
[18:53:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
[18:53:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[18:53:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
[18:53:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
[18:53:29] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546)
[18:53:29] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1541)
[18:53:29] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2605)
[18:53:29] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1469)
[18:53:29] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.<init>(WorldMySQLRegionManager.java:57)
[18:53:29] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RegionManager.loadAll(RegionManager.java:35)
[18:53:29] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:107)
[18:53:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[18:53:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319)
[18:53:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[18:53:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:357)
[18:53:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:317)
[18:53:29] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:414)
[18:53:29] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:379)
[18:53:29] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:333)
[18:53:29] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273)
[18:53:29] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:573)
[18:53:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:53:33] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[18:53:33] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:53:33] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:53:33] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:53:33] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2164)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2089)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
[18:53:33] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:53:33] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:53:33] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:53:33] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
[18:53:33] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
[18:53:33] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:247)
[18:53:33] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.ConnectDB(WorldMySQLRegionManager.java:718)
[18:53:33] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.load(WorldMySQLRegionManager.java:284)
[18:53:33] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RegionManager.loadAll(RegionManager.java:39)
[18:53:33] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:107)
[18:53:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[18:53:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319)
[18:53:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[18:53:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:357)
[18:53:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:317)
[18:53:33] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:414)
[18:53:33] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:379)
[18:53:33] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:333)
[18:53:33] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273)
[18:53:33] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:573)
[18:53:33] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:53:33] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'SurvivalServer1'@'%' to database 'SurvivalServer1_SurvivalServer-1'
[18:53:33] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:53:33] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:53:33] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:53:33] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1686)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1207)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2254)
[18:53:33] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
[18:53:33] [Server thread/WARN]: 	... 27 more
[18:53:33] [Server thread/INFO]: Redprotect: [[0;31;1m[21m[SurvivalServer1_SurvivalServer-1] Theres was an error while connecting to Mysql database! RedProtect will try to connect again in 15 seconds. If still not connecting, check the DB configurations and reload.[m][m
[18:53:33] [Server thread/WARN]: java.lang.NullPointerException
[18:53:33] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.load(WorldMySQLRegionManager.java:287)
[18:53:33] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RegionManager.loadAll(RegionManager.java:39)
[18:53:33] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:107)
[18:53:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[18:53:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319)
[18:53:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[18:53:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:357)
[18:53:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:317)
[18:53:33] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:414)
[18:53:33] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:379)
[18:53:33] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:333)
[18:53:33] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273)
[18:53:33] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:573)
[18:53:33] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by 7h3ev1l** [comment] 2016-05-09 16:01
I see this strange thing in error log:
`[18:53:33] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'SurvivalServer1'@'%' to database 'SurvivalServer1_SurvivalServer-1`


Database name is SurvivalServer1
but in log is like database 'SurvivalServer1_SurvivalServer-1'  strange..

**Comment by FabioZumbi12** [comment] 2016-05-12 15:24
Try to remove(and backup) all your redprotect database and start the plugin to create all again. I cant reproduce this on my tests...

**Comment by 7h3ev1l** [comment] 2016-05-12 15:40
I dont have any redprotect databases, i make fresh db and put it in config, i tried several times with numbers in password and name and without i get the same thing.

**Comment by 7h3ev1l** [comment] 2016-05-12 20:09
My mysql server is on other machine so i wonder can this be the problem ur plugin to use aways localhost/127.0.0.1, because my other plugins works perfect.

**Comment by Stuart74** [comment] 2016-05-13 03:10
If your SQL server is on a seperate machine you need to change localhost/127.0.0.1 to the ip of the SQL Server.    localhost/127.0.0.1 is only looking on the same machine noting more. Be sure that your other server will allow external logins on port 3306.

**Comment by FabioZumbi12** [comment] 2016-05-14 02:34
For some reasdon your server is giving a wrong world name like here:

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1

Where the world name is "-1" ... 

Try to do not use numbers on DB name and if possible, username too.

**Comment by 7h3ev1l** [comment] 2016-05-17 09:23
@Stuart74 I know how to connect to remote server my other plugins work!

@FabioZumbi12 I tried 2 times with different names of db/user names and password with numbers and without, i think the problem is because my world name is SurvivalServer-1 i cant change this!

**Comment by Stuart74** [comment] 2016-05-17 18:33
Deleted my comment sorry for trying to help hope you get it fixed

**Comment by 7h3ev1l** [comment] 2016-05-19 16:51
Bump

**Comment by 7h3ev1l** [comment] 2016-05-19 16:54
I wonder why tha hell 
https://github.com/FabioZumbi12/RedProtect/blob/master/src/main/java/br/net/fabiozumbi12/RedProtect/WorldMySQLRegionManager.java
line 51 is needed world.
The problem is somewhere there. Can u try to put world name with "" or something else i dont know but - is minus for mysql queries and probably mysql dont like my World name.

**Comment by FabioZumbi12** [comment] 2016-05-22 19:29
Humm! This make sense. Looking for similar problens i found this: http://stackoverflow.com/questions/676451/are-you-allowed-to-use-numbers-as-table-names-in-mysql

And the error is on line 57, where run CREATE DATABASE db_name.

Numbers on dbname will be invalid. I added '' as you suggested and you can try now: https://www.spigotmc.org/resources/redprotect-1-7-1-8-1-9-2-anti-grief-server-protection.15841/

**Closed** 2016-06-01 02:02 UTC
Labels: Bug, Waiting Feedback
