### ISSUE TITLE
[BUG] Sign disappears with left or right-click

### ISSUE THREAD

**Issue by antisoma** [FabioZumbi12/RedProtect#634] opened 2020-05-04 15:46 UTC
**Sign disappears**
Left or right-clicking a sign in a claim and it disappears.

This means players cannot dye the sign text.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place a sign in your claim
2. Left or right-click the sign
3. It disappears

**Expected behavior**
Normal left/right-click on block behaviour

**Server and plugins versions (please complete the following information):**
 - Server: 1.15.2 Tuinity
 - Plugin Version: RedProtect-7.6.6-b307-Universal
 - Java Version: Java 11

**Comment by antisoma** [comment] 2020-05-04 18:22
To add - I've confirmed this is RedProtect.  I removed all other plugins on a test server and the problem persisted.  Happy to share config files if helpful.

**Comment by FabioZumbi12** [comment] 2020-06-01 13:57
Its was caused by physics events. Should be fixed on latest release.

**Closed** 2020-07-26 17:56 UTC
Labels: Waiting Feedback
