### ISSUE TITLE
/rp flag doesn't work

### ISSUE THREAD

**Issue by Tommm24** [FabioZumbi12/RedProtect#1] opened 2015-06-12 18:10 UTC
Hey there

I love your new flag GUI menu. I saw it on another server and we upgraded our version of RP. 

Upon typing /rp flag to get the GUI we get an error message: An internal error occurred while attempting to perform this command. 

I had a look in the console and this is what was there: http://pastebin.com/K367fxMH

Any ideas?
Thanks in advance!

**Comment by FabioZumbi12** [comment] 2015-06-12 20:04
Looking the error we have this line:

"Caused by: java.lang.NoClassDefFoundError: org/bukkit/inventory/ItemFlag"

RedProtect didnt find the class from your Spigot version. What SPigot version you is using? Seem you is using java 1.7 too... i recommend you upgrade to 1.8.

I will make some tests too to see if i find the same error.
Thanks.

**Comment by FabioZumbi12** [comment] 2015-06-13 05:24
I think is fixed on version 5.4.0, updated today! Try it ;)

**Comment by Tommm24** [comment] 2015-06-13 05:38
Thanks for the second update - just tried it and I still seem to have an error. (sorry for being annoying)
http://pastebin.com/LXQzR1qY

I will look into it more when I wake up :P 

Thanks :)

**Comment by FabioZumbi12** [comment] 2015-06-30 00:48
I tink is fixed on this version: http://dev.bukkit.org/bukkit-plugins/region-protect-plus/files/71-red-protect-v5-4-3/

Try it.

**Comment by Tommm24** [comment] 2015-06-30 10:06
Works now! Thank you for remembering to reply to me! 

Also can you add us on to your list of servers? We are:

Radcraft - Survival Economy with Minigames

Thanks for your help :)

PS. I see you played on lethal tactics too? I played on there back in the day - I was staff there too! What was your username? :P

**Comment by FabioZumbi12** [comment] 2015-07-01 00:54
Oh good! You forgot to type your server ip.

On this week i joined on lethal tactics to see how Rp is working, but a years ago i have played on that server :) Its a excelente server!

**Comment by Tommm24** [comment] 2015-07-01 08:30
Woops sorry!

Radcraft: mc.radcraft.co.uk - Survival Economy with Minigames :)

I played it years ago too! I was sub-admin :) 
what was your username? I was MinecraftTommm :)

**Comment by FabioZumbi12** [comment] 2015-07-01 19:59
Added your server :)
I played with this same nick, FabioZumbi12, i builded a litte house around the spawn protection, but after world reset, i never more played on LTT, but i have maded my server based on the LTT :)

**Closed** 2015-08-16 06:34 UTC
